In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import Select, WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import time as t
import os

In [12]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import os
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import QuantileTransformer
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import SelectKBest, RFE, f_regression, SequentialFeatureSelector
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.linear_model import LassoLars
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import TweedieRegressor

In [2]:
# salary_data_url = 'https://overthecap.com/contract-history/quarterback'
# driver = webdriver.Chrome(service= Service())
# driver.get(salary_data_url)
# driver.maximize_window()
# t.sleep(3)

In [3]:
# tr_elements_stats = driver.find_elements(By.XPATH, '''//tr''')

In [4]:
# master_list = []
# for i in range(len(tr_elements_stats)):
#     if i > 0:
#         master_list.append(tr_elements_stats[i].text.split())

In [5]:
# master_list

In [6]:
# salaries_data = pd.DataFrame(master_list)

In [7]:
# salaries_data.to_csv('salaries_data', sep=',', index=False, encoding='utf-8')

In [8]:
# tr_elements_stats[].text

In [9]:
df1 = pd.read_csv('2016_data')
df2 = pd.read_csv('2017_data')
df3 = pd.read_csv('2018_data')
df4 = pd.read_csv('2019_data')
df5 = pd.read_csv('2020_data')
df6 = pd.read_csv('2021_data')
df7 = pd.read_csv('2022_data')

In [42]:
df = pd.concat([df1,df2,df3,df4,df5,df6,df7])

In [34]:
the_df.shape

(277, 18)

In [21]:
pd.concat([df1,df2,df3,df4,df5,df6,df7]).head()

,0,0.1,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,year
0,Drew Brees,NO,2.42,6.2,7.6,-1.4,17.5,52.2,-1.0,673,5208,37,15,101.7,70.0,65.4,4.6,2016
1,Matt Ryan,ATL,2.64,7.2,9.0,-1.8,21.0,61.4,-0.2,534,4944,38,7,117.1,69.9,62.4,7.4,2016
2,Kirk Cousins,WAS,2.81,7.5,9.4,-1.9,14.0,57.5,0.7,605,4917,25,12,97.4,67.1,58.7,8.4,2016
3,Aaron Rodgers,GB,2.87,6.3,9.2,-3.0,16.4,60.8,0.8,610,4428,40,7,104.2,65.7,62.2,3.5,2016
4,Philip Rivers,LAC,2.65,6.7,8.8,-2.1,18.7,57.6,0.0,578,4386,33,21,87.9,60.4,61.7,-1.3,2016

In [25]:
list_of_features = the_df.columns[2:6].to_list()

In [57]:
target = the_df.columns[9]

In [58]:
train, validate, test = split_data(df, target)

In [59]:
X_train, X_validate, X_test, y_train, y_validate, y_test = get_X_train_val_test(train, validate, test, list_of_features, target)

In [69]:
metrics_train_df, metrics_validate_df, metrics_test_df = get_model_numbers(X_train, X_validate, X_test, y_train, y_validate, y_test)

In [ ]:
list_of_features = the_df.columns[2:6].to_list()
target = the_df.columns[9]
train, validate, test = split_data(df, target)
X_train, X_validate, X_test, y_train, y_validate, y_test = get_X_train_val_test(train, validate, test, list_of_features, target)
metrics_train_df, metrics_validate_df, metrics_test_df = get_model_numbers(X_train, X_validate, X_test, y_train, y_validate, y_test)

In [61]:
metrics_train_df

                      model_train  rmse  r2
0                        baseline   152   0
1     ordinary least squared(OLS)   152   0
2                lasso lars(lars)   152   0
3    Polynomial Regression(poly2)   143  12
4  Generalized Linear Model (GLM)   152   0

In [62]:
metrics_validate_df

                   model_validate  rmse  r2
0                        baseline   152   0
1     ordinary least squared(OLS)   145   2
2                lasso lars(lars)   147   0
3    Polynomial Regression(poly2)   146   1
4  Generalized Linear Model (GLM)   145   2

In [70]:
metrics_test_df

                   model_validate  rmse  r2
0                        baseline   152   0
1     ordinary least squared(OLS)   171   0
2                lasso lars(lars)   172  -1
3    Polynomial Regression(poly2)   168   3
4  Generalized Linear Model (GLM)   171   0

In [49]:
def get_X_train_val_test(train,validate, test, list_of_features,target):
    '''
    geting the X's and y's and returns them
    '''
    X_train = train[list_of_features]
    X_validate = validate[list_of_features]
    X_test = test[list_of_features]
    
    y_train = train[target]
    y_validate = validate[target]
    y_test = test[target]

    return X_train, X_validate, X_test, y_train, y_validate, y_test

In [38]:
def split_data(df, target):
    '''
    Takes in a dataframe and returns train, validate, test subset dataframes
    '''
    
    
    train, test = train_test_split(df,
                                   test_size=.2, 
                                   random_state=123, 
                                   
                                   )
    train, validate = train_test_split(train, 
                                       test_size=.25, 
                                       random_state=123, 
                                       
                                       )
    
    return train, validate, test

In [15]:
def metrics_reg(y, yhat):
    '''
    send in y_true, y_pred and returns rmse, r2
    '''
    rmse = mean_squared_error(y, yhat, squared=False)
    r2 = r2_score(y, yhat)
    return rmse, r2

In [68]:
def get_model_numbers(X_train, X_validate, X_test, y_train, y_validate, y_test):
    '''
    This function takes the data and runs it through various models and returns the
    results in pandas dataframes for train, test and validate data
    '''
    baseline = y_train.mean()
    baseline_array = np.repeat(baseline, len(X_train))
    rmse, r2 = metrics_reg(y_train, baseline_array)

    metrics_train_df = pd.DataFrame(data=[
    {
        'model_train':'baseline',
        'rmse':rmse,
        'r2':r2
    }
    ])
    metrics_validate_df = pd.DataFrame(data=[
    {
        'model_validate':'baseline',
        'rmse':rmse,
        'r2':r2
    }
    ])
    metrics_test_df = pd.DataFrame(data=[
    {
        'model_validate':'baseline',
        'rmse':rmse,
        'r2':r2
    }
    ])


    Linear_regression1 = LinearRegression()
    Linear_regression1.fit(X_train,y_train)
    predict_linear = Linear_regression1.predict(X_train)
    rmse, r2 = metrics_reg(y_train, predict_linear)
    metrics_train_df.loc[1] = ['ordinary least squared(OLS)', rmse, r2]

    predict_linear = Linear_regression1.predict(X_validate)
    rmse, r2 = metrics_reg(y_validate, predict_linear)
    metrics_validate_df.loc[1] = ['ordinary least squared(OLS)', rmse, r2]
    
    predict_linear = Linear_regression1.predict(X_test)
    rmse, r2 = metrics_reg(y_test, predict_linear)
    metrics_test_df.loc[1] = ['ordinary least squared(OLS)', rmse, r2]


    lars = LassoLars()
    lars.fit(X_train, y_train)
    pred_lars = lars.predict(X_train)
    rmse, r2 = metrics_reg(y_train, pred_lars)
    metrics_train_df.loc[2] = ['lasso lars(lars)', rmse, r2]

    pred_lars = lars.predict(X_validate)
    rmse, r2 = metrics_reg(y_validate, pred_lars)
    metrics_validate_df.loc[2] = ['lasso lars(lars)', rmse, r2]
    
    pred_lars = lars.predict(X_test)
    rmse, r2 = metrics_reg(y_test, pred_lars)
    metrics_test_df.loc[2] = ['lasso lars(lars)', rmse, r2]


    pf = PolynomialFeatures(degree=2)
    X_train_degree2 = pf.fit_transform(X_train)

    pr = LinearRegression()
    pr.fit(X_train_degree2, y_train)
    pred_pr = pr.predict(X_train_degree2)
    rmse, r2 = metrics_reg(y_train, pred_pr)
    metrics_train_df.loc[3] = ['Polynomial Regression(poly2)', rmse, r2]

    X_validate_degree2 = pf.transform(X_validate)
    pred_pr = pr.predict(X_validate_degree2)
    rmse, r2 = metrics_reg(y_validate, pred_pr)
    metrics_validate_df.loc[3] = ['Polynomial Regression(poly2)', rmse, r2]

    X_test_degree2 = pf.transform(X_test)
    pred_pr = pr.predict(X_test_degree2)
    rmse, r2 = metrics_reg(y_test, pred_pr)
    metrics_test_df.loc[3] = ['Polynomial Regression(poly2)', round(rmse,2), r2]

    
    glm = TweedieRegressor(power=2, alpha=0)
    glm.fit(X_train, y_train)
    
    pred_glm = glm.predict(X_train)
    rmse, r2 = metrics_reg(y_train, pred_glm)
    metrics_train_df.loc[4] = ['Generalized Linear Model (GLM)', rmse, r2]

    pred_glm = glm.predict(X_validate)
    rmse, r2 = metrics_reg(y_validate, pred_glm)
    metrics_validate_df.loc[4] = ['Generalized Linear Model (GLM)', rmse, r2]
    
    pred_glm = glm.predict(X_test)
    rmse, r2 = metrics_reg(y_test, pred_glm)
    metrics_test_df.loc[4] = ['Generalized Linear Model (GLM)', rmse, r2]


    metrics_train_df.rmse = metrics_train_df.rmse.astype(int)
    metrics_validate_df.rmse = metrics_validate_df.rmse.astype(int)
    metrics_test_df.rmse = metrics_test_df.rmse.astype(int)
    print()
    metrics_train_df.r2 = (metrics_train_df.r2 * 100).astype(int)
    metrics_validate_df.r2 = (metrics_validate_df.r2 * 100).astype(int)
    metrics_test_df.r2 = (metrics_test_df.r2 * 100).astype(int)

    return metrics_train_df, metrics_validate_df, metrics_test_df